Error in file(file, "rt") : cannot open the connection

